networks:
  default:
    driver: bridge
    ipam:
      driver: default
services:
  ytdlwl:
    build: .
    volumes:
      - /mnt/Videos:/var/Videos
    secrets:
      - yt-cookies
      - ssh-key-prv

secrets:
  yt-cookies:
    file: /mnt/Videos/cookies/cookies.txt
  ssh-key-prv:
    file: ../.ssh/id_ed25519


